/*

 ROCKY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Rocky[] =
{
  0x3C,0x3C,0x60,0x7C,0x64,0x76,0xE1,0xFF,
  0x0C,0xB0,0x1E,0x52,0x00,0x74,0x22,0x36,
  0x3C,0x3C,0x60,0x7C,0x64,0x76,0xC1,0xDF,
  0x0C,0xB0,0x2E,0xF2,0x00,0x74,0x22,0x36
};

/* End of ROCKY.C */
